CREATE TABLE IF NOT EXISTS "korean_stock"
(
    id                   TEXT        PRIMARY KEY,
    date                 DATE        NOT NULL,
    isu                  TEXT        NOT NULL,
    name                 TEXT        NOT NULL,
    market               TEXT        NOT NULL,
    sector               TEXT        ,
    end_price            BIGINT      NOT NULL,
    change_price         BIGINT      NOT NULL,
    change_rate          REAL        NOT NULL,
    start_price          BIGINT      NOT NULL,
    highest_price        BIGINT      NOT NULL,
    lowest_price         BIGINT      NOT NULL,
    trade_volume         BIGINT      NOT NULL,
    trade_amount         BIGINT      NOT NULL,
    market_cap           BIGINT      NOT NULL,
    number_of_share      BIGINT      NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "korean_etf"
(
    id                      TEXT        PRIMARY KEY,
    date                    DATE        NOT NULL,
    isu                     TEXT        NOT NULL,
    name                    TEXT        NOT NULL,
    end_price               BIGINT      NOT NULL,
    change_price            BIGINT      NOT NULL,
    change_rate             REAL        NOT NULL,
    net_value               FLOAT       NOT NULL,
    start_price             BIGINT      NOT NULL,
    highest_price           BIGINT      NOT NULL,
    lowest_price            BIGINT      NOT NULL,
    trade_volume            BIGINT      NOT NULL,
    trade_amount            BIGINT      NOT NULL,
    market_cap              BIGINT      NOT NULL,
    net_cap_value           BIGINT      NOT NULL,
    number_of_share         BIGINT      NOT NULL,
    base_index_name         TEXT        NOT NULL,
    base_index_end_point    FLOAT       NOT NULL,
    base_index_change_point FLOAT       NOT NULL,
    base_index_change_rate  REAL        NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "korean_stock_moving_average"
(
    id                   TEXT        PRIMARY KEY,
    "date"               DATE        NOT NULL,
    "name"               TEXT        NOT NULL,
    start_price_3        BIGINT      ,
    end_price_3          BIGINT      ,
    highest_price_3      BIGINT      ,
    lowest_price_3       BIGINT      ,
    start_price_5        BIGINT      ,
    end_price_5          BIGINT      ,
    highest_price_5      BIGINT      ,
    lowest_price_5       BIGINT      ,
    start_price_7        BIGINT      ,
    end_price_7          BIGINT      ,
    highest_price_7      BIGINT      ,
    lowest_price_7       BIGINT      ,
    start_price_10        BIGINT      ,
    end_price_10          BIGINT      ,
    highest_price_10      BIGINT      ,
    lowest_price_10       BIGINT      ,
    start_price_15        BIGINT      ,
    end_price_15          BIGINT      ,
    highest_price_15      BIGINT      ,
    lowest_price_15       BIGINT      ,
    start_price_25        BIGINT      ,
    end_price_25          BIGINT      ,
    highest_price_25      BIGINT      ,
    lowest_price_25       BIGINT      ,
    start_price_50        BIGINT      ,
    end_price_50          BIGINT      ,
    highest_price_50      BIGINT      ,
    lowest_price_50       BIGINT      ,
    start_price_75        BIGINT      ,
    end_price_75          BIGINT      ,
    highest_price_75      BIGINT      ,
    lowest_price_75       BIGINT      ,
    start_price_100       BIGINT      ,
    end_price_100         BIGINT      ,
    highest_price_100     BIGINT      ,
    lowest_price_100      BIGINT      ,
    start_price_120       BIGINT      ,
    end_price_120         BIGINT      ,
    highest_price_120     BIGINT      ,
    lowest_price_120      BIGINT      ,
    
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);